services:
  backend: 
    image: node:alpine
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: sh -c "cd /app && npm install && npm start"

  frontend:
    image: node:alpine
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "cd /app && npm install && npm start"